# Análise de Risco em Saúde Única

Os cálculos e análises no curso serão realizados com auxílio de notebooks e python. Inicialmente é preciso que nos familiarizemos com os principais pacotes que serão utilizados:

* Numpy
* Scipy
* Statsmodels
* Matplotlib
* Seaborn

## Numpy

O numpy é uma biblioteca que fornece um array multidimensional, além de vários objetos derivados (matizes e arrays mascarados) e um conjunto de rotinas para operação em arrays (matematicas, logicas, manipulação de formato, ordenamento , seleção, I/O, transformadas de Fourier, álgebra linear básica, estatística básica, simulações e muito mais).

Caracteristicas de um array:

* Possui tamanho fixo estabelecido na criação. Qualquer alteração irá gerar um novo array.
* Os elementos do array são do mesmo tipo.
* Facilita a realização de operações matemáticas em grande número de registros.
* Várias aplicações em python utilizam arrays numpy.

### O que torna o numpy tão rápido?
* **_Vetorização_**: processo de aplicar uma operação em um array inteiro de uma só vez, em vez de elemento por elemento. O NumPy executa essas operações em um nível de código C compilado, o que é ordens de magnitude mais rápido do que usar um laço for em Python. Exemplo:

In [2]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a*b)

[ 4 10 18]


Este código é mais simples e rápido que o seguinte:

In [7]:
c = np.empty(3)
for i in range(3):
    c[i] = a[i]*b[i]

print(c)

[ 4. 10. 18.]


* **_Broadcasting_**: é o conjunto de regras que o NumPy utiliza para permitir operações entre arrays de diferentes formatos e tamanhos. O broadcasting "estica" virtualmente o array menor para que seu formato corresponda ao do array maior, permitindo que a operação vetorizada ocorra.

Isso evita a necessidade de criar cópias desnecessárias dos dados apenas para que os tamanhos correspondam.

In [10]:
a = np.array([1,2,3])
b = 2
print(a*b)

[2 4 6]


![Broadcasting](https://numpy.org/doc/stable/_images/broadcasting_1.png)